# SPDX-FileCopyrightText: 2023 Jisc Services Limited
# SPDX-FileContributor: Joe Pitt
#
# SPDX-License-Identifier: GPL-3.0-only

version: '3'
services:
  # misp-docker containers here
  splunk-forwarder:
    hostname: misp_splunk
    image: jisccti/misp-splunk-forwarder:latest
    depends_on:
      web:
        condition: service_healthy
    environment:
      - FQDN=${FQDN:-misp.local}
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD:-ChangeMeChangeMeChangeMe}
      - SPLUNK_START_ARGS=--accept-license
      - HEC_URI=${SPLUNK_HEC_URI}
      - HEC_KEY=${SPLUNK_HEC_KEY}
      - HEC_VERIFY=${SPLUNK_HEC_VERIFY:-false}
      - INDEX=${SPLUNK_INDEX:-default}
    volumes:
      - ./persistent/${COMPOSE_PROJECT_NAME}/splunk/config/:/opt/splunkforwarder/etc/apps/misp_docker/local/
      - ./persistent/${COMPOSE_PROJECT_NAME}/data/:/opt/misp_docker/:ro
      # persist the fishbucket so log entries are not reingested on restart
      - ./persistent/${COMPOSE_PROJECT_NAME}/splunk/fishbucket/:/opt/splunkforwarder/var/lib/splunk/fishbucket/
      - ./persistent/${COMPOSE_PROJECT_NAME}/data/tmp/logs/:/var/logs/MISP/:ro
    restart: unless-stopped
